server:
  port: 10010
spring:
  application:
    name:leyou-gateway
eureka:
  client:
    registry-fetch-interval-secounds:5
    service-url:
      defaultZone:http://127.0.0.1:10086/eureka
zuul:
  perfix:/api #路由路径前缀